### ISSUE TITLE
Python Nordeste 2018

### ISSUE THREAD

**Issue by liviagabos** [FernandaBernardo/eventos-tech#13]
- Nome do evento: Python Nordeste 2018
- Data:24, 25 e 26 de maio
- Local: Campina Grande/PB
- Descrição breve do evento: A Python Nordeste é a maior conferência regional da comunidade Python no Brasil, que ocorre anualmente em cidades da região nordeste. Em um contexto bem diversificado e dedicado à troca de experiências e conhecimento, o evento é focado em indivíduos de diversas áreas e origens, sem distinção do seu grau de conhecimento da linguagem. A Python Nordeste possui um código de conduta que assegura a todos os participantes um ambiente livre de preconceitos, possibilitando a abordagem amigável de qualquer tema dentro do universo Python.
- Valor do ingresso:
- Site do evento: https://speakerfight.com/events/python-nordeste-2018-24-25-e-26-de-maio-campina-grandepb/

**Comment by FernandaBernardo** [comment]
Brigada @liviagabos 😊 

Já adicionei!
