### ISSUE TITLE
DevCamp 2017

### ISSUE THREAD

**Issue by marttosc** [FernandaBernardo/eventos-tech#2]
Evento:
DevCamp 2017

Data:
02/06/2017

Local:
Av. Guilherme Campos, 500, Bloco II
Campinas / SP – CEP: 13087-901)
(Anexo ao Parque D. Pedro Shopping)

Descrição:
Conferência de desenvolvimento de software do interior do Estado de São Paulo

Valor do ingresso:
R$ 310,00

Site do evento:
www.devcamp.com.br

**Comment by FernandaBernardo** [comment]
Muito obrigada @marttosc 😊
